covered_area_layer:
  default_value: 128          # in range of [0, 255]

landmines_layer:
  num_parts: 18
  radius: 0.45
  landmines_topic: '/HRATC_FW/set_mine'

obstacles_layer:
  num_parts: 18
  radius: 0.25
  obstacles_topic: '/HRATC_FW/set_mine'
