# coil signal sampling related paremeters
derivative_sample_time: 0.1
low_coil_signal_threshold: 0.45
high_coil_signal_threshold: 0.65
coil_signal_filter_number_of_observations: 8
number_of_derivatives: 6

sampling_end_interval: 3.0
max_coil_signal: 0.975
max_tolerance: 0.025
min_radius: 0.05
max_radius: 1.0
std_radius: 0.5
