coil_signal_threshold: 0.9
coil_signal_filter_number_of_observations: 3
linear_velocity_x: 0.2
angular_velocity_z: 0.6
Kp: 1.0
min_coil_signal: 0.6
max_coil_signal: 1.0
coil_signal_increment: 0.2
coil_signal_tolerance: 0.01
safe_coil_signal: 0.4
safe_time: 5.0
