low_coil_signal_threshold: 0.5
high_coil_signal_threshold: 0.9
coil_signal_filter_number_of_observations: 4
linear_velocity_x: 0.1
angular_velocity_z: 0.3
angular_Kp: 1.5
linear_Kp: 1.5
linear_tolerance: 0.05
angular_tolerance: 0.01
min_coil_signal: 0.6
max_coil_signal: 0.95
safe_time: 10.0
sample_time: 0.25
