linear_velocity_x: 0.1
angular_velocity_z: 0.3
Kp: 1.0
min_coil_signal: 0.7
max_coil_signal: 1.0
coil_signal_increment: 0.1
coil_signal_tolerance: 0.01
safe_coil_signal: 0.4
threshold: 0.5
safe_time: 2.0
