topics:
-
  name    : navigation
  topic   : move_base/cmd_vel
  timeout : 0.0
  priority: 50
-
  name    : metal_scanner
  topic   : metal_scanner/cmd_vel
  timeout : 1.5
  priority: 100

locks:
-
  name    : scanning
  topic   : scanning
  timeout : 0.0
  priority: 80
-
  name    : moving_away
  topic   : moving_away
  timeout : 0.0
  priority: 80
