map_coverage_offset: 0.1
map_coverage_margin: 0.9
landmine_radius_area: 1.0
waypoints:
  manual: true
  size: 11
  waypoint0:
    x: 1.08414
    y: -0.203271
  waypoint1:
    x: 0.592041
    y: -0.198308
  waypoint2:
    x: -0.127722
    y: -0.181265
  waypoint3:
    x: 1.56829
    y: -0.406542
  waypoint4:
    x: -2.26997
    y: -0.405549
  waypoint5:
    x: 4.33658
    y: -0.813085
  waypoint6:
    x: -5.8099
    y: -1.21665
  waypoint7:
    x: -6.1883
    y: 3.16767
  waypoint8:
    x: 7.2281
    y: 4.03173
  waypoint9:
    x: 6.7573
    y: -1.82944
  waypoint10:
    x: 0.0
    y: 0.0
