obstacle_range: 2.0       # determines the maximum range sensor reading that will result in an obstacle being put into the costmap.
raytrace_range: 3.0       # determines the range to which we will raytrace freespace given a sensor reading.
inflation_radius: 0.7     # should be set to the maximum distance from obstacles at which a cost should be incurred.

#---standard pioneer footprint---
#---(in inches)---
#footprint: [ [10, -2], [7, -2], [7, -7], [-7.5, -7], [-10, 0], [-7.5, 7], [7, 7], [7, 2], [10, 2] ]
#---(in meters)---
#footprint: [ [0.254, -0.0508], [0.1778, -0.0508], [0.1778, -0.1778], [-0.1905, -0.1778], [-0.254, 0], [-0.1905, 0.1778], [0.1778, 0.1778], [0.1778, 0.0508], [0.254, 0.0508] ]

#---pioneer AT footprint:---
#---(in inches)---
#footprint: [ [13, -2], [10, -2], [10, -10], [-10, -10], [-10, 10], [10, 10], [10, 2], [13, 2] ]
#---(in meters)---
#footprint: [ [0.3302, -0.0508], [0.254, -0.0508], [0.254, -0.254], [-0.254, -0.254], [-0.254, 0.254], [0.254, 0.254], [0.254, 0.0508], [0.3302, 0.0508] ]

#---pioneer AT with metal detector (HRATC2017) footprint:---
#---(in inches)---
#footprint: [ [23, -10], [-10, -10], [-10, 10], [23, 10] ]
#---(in meters)---
footprint: [ [0.585, -0.254], [-0.254, -0.254], [-0.254, 0.254], [0.585, 0.254] ]

transform_tolerance: 0.5
map_type: 'costmap'

plugins:
- {name: static_layer, type: 'costmap_2d::StaticLayer'}
#- {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
- {name: obstacles_layer, type: 'hratc2017::ObstaclesLayer'}
- {name: landmines_layer, type: 'hratc2017::LandminesLayer'}
- {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
#- {name: covered_area_layer, type: 'hratc2017::CoveredAreaLayer'}

observation_sources: 'laser_scan_sensor'      # defines a list of sensors that are going to be passing information to the costmap separated by spaces.
laser_scan_sensor: {sensor_frame: 'laser', data_type: 'LaserScan', topic: 'scan', marking: true, clearing: true, expected_update_rate: 0.2}
